local schema = {
    -- Array For tab and INI ordering purposes
    Sections = {
        'General', 
        'DPS', 
        'Heals', 
        'Buffs', 
        'Melee', 
        'Burn', 
        'Mez', 
        'AE', 
        'OhShit', 
        'Pet', 
        'Pull', 
        'Aggro', 
        'Bandolier', 
        'Cures', 
        'GoM', 
        'Merc', 
        'AFKTools', 
        'GMail', 
        'MySpells', 
        'SpellSet',
    },
    General={
        Properties={
            CampRadius={-- int (30)
                Type='NUMBER',
                Min=0,
            },
            CampRadiusExceed={-- int (400)
                Type='NUMBER',
                Min=0,
            },
            ReturnToCamp={-- int (0)
                Type='SWITCH',
            },
            ReturnToCampAccuracy={-- int (10)
                Type='NUMBER',
                Min=5,
            },
            ChaseAssist={-- int (0)
                Type='SWITCH',
            },
            ChaseDistance={-- int (25)
                Type='NUMBER',
                Min=0,
            },
            MedOn={-- int (1)
                Type='SWITCH',
            },
            MedStart={-- string (20)
                Type='NUMBER',
                Min=0,
                Max=100,
            },
            SitToMed={-- not from LoadIni call??
                Type='NUMBER',
                Min=0,
            },
            LootOn={-- int (0)
                Type='SWITCH',
            },
            RezAcceptOn={--switch + extra option, string, (0|96)
                Type='STRING',
            },
	    --[[
            RezAcceptOn={--switch + extra option 0/1|96
                Type='MULTIPART',
                Parts={
                    [1]={
                        Name='On|Off',
                        Type='SWITCH'
                    },
                    [2]={
                        Name='Min. Pct',
                        Type='NUMBER',
                        Min=0,
                        Max=100,
                    },
                },
            },
	    --]]
            AcceptInvitesOn={-- int (1)
                Type='SWITCH',
            },
            GroupWatchOn={--switch + extra options 0/1/2/3|MedAt%|Classes
                Type='STRING',
            },
            CastingInterruptOn={-- int (0)
                Type='SWITCH',
            },
            EQBCOn={--switch + extra option
                Type='STRING',
            },
            DanNetOn={--switch + extra option
                Type='STRING',
            },
            DanNetDelay={-- int (20)
                Type='NUMBER',
            },
            MiscGem={-- int (8)
                Type='NUMBER',
                Min=1,
                Max=13,
            },
            MiscGemLW={-- int (0)
                Type='NUMBER',
                Min=1,
                Max=13,
            },
            MiscGemRemem={-- int (1)
                Type='SWITCH',
            },
            TwistOn={
                Type='SWITCH',
            },
            TwistMed={
                Type='STRING',
            },
            TwistWhat={
                Type='STRING',
            },
            GroupEscapeOn={-- int (0)
                Type='SWITCH',
            },
            CampfireOn={-- int (0)
                Type='SWITCH',
            },
            DPSMeter={-- int (1)
                Type='SWITCH',
            },
            Scatter={-- int (0)
                Type='SWITCH',
            },
            CheerPeople={-- int (0)
                Type='SWITCH',
            },
            BuffWhileChasing={--bool (1)
                Type='SWITCH',
            },
            SwitchWithMA={-- bool (FALSE)
                Type='SWITCH',
            },
            CastRetries={ -- new beta int (3)
                Type='NUMBER',
            },
            --Role string (Assist)
            --GemStuckAbility string (NULL)
            --HoTTOn int (0)
            --MoveCloserIfNoLOS int (0)
            --IRCOn int (0)
            --TravelOnHorse bool (FALSE)
        }
    },
    SpellSet={
        Properties={
            LoadSpellSet={
                Type='NUMBER',
                Min=0,
                Max=2,
            },
            SpellSetName={
                Type='STRING'
            },
        },
    },
    Melee={
        Controls={
            On={
                Type='SWITCH',
            },
        },
        Properties={
            AssistAt={
                Type='NUMBER',
                Min=1,
                Max=100,
            },
            FaceMobOn={
                Type='SWITCH',
            },
            MeleeDistance={
                Type='NUMBER',
                Min=0,
            },
            StickHow={
                Type='STRING',
            },
            MeleeTwistOn={
                Type='SWITCH',
            },
            MeleeTwistWhat={
                Type='STRING',
            },
            AutoFireOn={
                Type='SWITCH',
            },
            UseMQ2Melee={
                Type='SWITCH',
            },
            Autohide={ -- rogue only
                Type='SWITCH',
            },
            BeforeCombat={
                Type='SPELL',
            },
            RogueTimerEight={-- new beta? rogue only
                Type='SPELL',
            },
            TargetSwitchingOn={
                Type='SWITCH',
            },
            DismountDuringFights={
                Type='SWITCH',
            },
            TankAllMobs={ -- new beta?
                Type='SWITCH'
            }
        },
    },
    DPS={
        Controls={
            On={
                Type='NUMBER',
                Min=0,
                Max=2,
            },
            COn=true,
        },
        Properties={
            DPS={
                Type='LIST',
                Max=40,
                Conditions=true,
            },
            DPSSkip={
                Type='NUMBER',
                Min=1,
                Max=100,
            },
            DPSInterval={
                Type='NUMBER',
                Min=0,
            },
            DebuffAllOn={
                Type='NUMBER',
                Min=0,
                Max=2,
            },
            StayAwayToCast={-- new beta?
                Type='SWITCH'
            },
        },
    },
    Buffs={
        Controls={
            On={
                Type='SWITCH',
            },
            COn=true,
        },
        Properties={
            Buffs={
                Type='LIST',
                Max=20,
                Conditions=true,
            },
            RebuffOn={
                Type='SWITCH',
            },
            CheckBuffsTimer={
                Type='NUMBER',
                Min=0,
            },
            PowerSource={
                Type='STRING',
            },
            BegOn={
                Type='SWITCH',
            },
            BegPermission={
                Type='STRING',
            },
            Beg={
                Type='LIST',
                Max=20,
                Conditions=false,
            },
            -- BuffCacheingDelay int 300
        }
    },
    Heals={
        Controls={
            On={
                Type='SWITCH',
            },
            COn=true,
        },
        Properties={
            Heals={
                Type='LIST',
                Max=15,
                Conditions=true,
            },
            XTarHeal={
                Type='STRING',
            },
            AutoRezOn={
                Type='SWITCH',
            },
            AutoRezWith={
                Type='SPELL',
            },
            HealGroupPetsOn={
                Type='SWITCH',
            },
            InterruptHeals={
                Type='NUMBER',
                Min=0,
            },
        },
    },
    Cures={
        Controls={
            On={
                Type='SWITCH',
            },
        },
        Properties={
            Cures={-- loaded once without conds and once with? no COn switch tho
                Type='LIST',
                Max=5,
                Conditions=true,
            },
        },
    },
    Mez={
        Controls={
            On={
                Type='NUMBER',
                Min=0,
                Max=3,
            },
        },
        --Classes={brd=1,enc=1},
        Properties={
            MezRadius={
                Type='NUMBER',
                Min=0,
            },
            MezMinLevel={
                Type='NUMBER',
                Min=1,
            },
            MezMaxLevel={
                Type='NUMBER',
                Min=1,
            },
            MezStopHPs={
                Type='NUMBER',
                Min=1,
                Max=100,
            },
            MezSpell={
                Type='SPELL',
            },
            MezAESpell={
                Type='SPELL',
            }
        }
    },
    Pet={
        Controls={
            On={
                Type='SWITCH',
            },
        },
        Properties={
            PetToys={
                Type='LIST',
                Max=6,
                Conditions=false,
            },
            PetSpell={
                Type='SPELL',
            },
            PetFocus={
                Type='SPELL',
            },
            PetShrinkOn={
                Type='SWITCH',
            },
            PetShrinkSpell={
                Type='SPELL',
            },
            PetHoldOn={
                Type='SWITCH',
            },
            PetBuffsOn={
                Type='SWITCH',
            },
            PetBuffs={
                Type='LIST',
                Max=8,
                Conditions=false,
            },
            PetCombatOn={
                Type='SWITCH',
            },
            PetAssistAt={
                Type='NUMBER',
                Min=1,
                Max=100,
            },
            PetBreakMezSpell={
                Type='SPELL',
            },
            PetRampPullWait={
                Type='SWITCH',
            },
            PetSuspend={
                Type='SWITCH',
            },
            MoveWhenHit={
                Type='SWITCH',
            },
            PetToysOn={
                Type='SWITCH',
            },
            --PetToysGave=internal?
            --PetForceHealOnMed int
            --PetBehind bool
        }
    },
    Pull={
        Properties={
            PullWith={
                Type='STRING',
            },
            MaxRadius={
                Type='NUMBER',
                Min=1,
            },
            MaxZRange={
                Type='NUMBER',
                Min=1,
            },
            PullWait={
                Type='NUMBER',
                Min=0,
            },
            PullRoleToggle={
                Type='SWITCH',
            },
            PullTwistOn={
                Type='SWITCH',
            },
            ChainPull={
                Type='SWITCH',
            },
            ChainPullHP={
                Type='NUMBER',
                Min=1,
                Max=100,
            },
            ChainPullPause={
                Type='STRING',
            },
            PullPause={
                Type='STRING',
            },
            PullLevel={
                Type='STRING',
            },
            PullMeleeStick={
                Type='SWITCH',
            },
            UseWayPointZ={
                Type='SWITCH',
            },
            PullArcWidth={
                Type='NUMBER',
                Min=0,
                Max=360,
            },
            -- CheckForMemblurredMobsInCamp int (0)
            -- PullCond string (TRUE)
            -- PrePullCond string (TRUE)
            -- PullNamedsFirst int (0)
            -- ActNatural int (1)
            -- UseCalm int (0)
            -- CalmWith string
            -- CalmRadius int
            -- GrabDeadGroupMembers int (1)
        },
    },
    Merc={
        Controls={
            On={
                Type='SWITCH',
            },
        },
        Properties={
            MercAssistAt={
                Type='NUMBER',
                Min=1,
                Max=100,
            },
            AutoRevive={
                Type='SWITCH',
            },
        },
    },
    Burn={
        Controls={
            COn=true,
        },
        Properties={
            Burn={
                Type='LIST',
                Max=15,
                Conditions=true,
            },
            BurnAllNamed={
                Type='NUMBER',
                Min=0,
                Max=2,
            },
            UseTribute={
                Type='SWITCH',
            },
            BurnText={
                Type='STRING',
            },
        },
    },
    AFKTools={
        Controls={
            On={
                Type='SWITCH',
            },
        },
        Properties={
            AFKGMAction={-- int (1)
                Type='NUMBER',
                Min=0,
                Max=4,
            },
            AFKPCRadius={-- int (500)
                Type='NUMBER',
                Min=0,
            },
            CampOnDeath={-- int (0)
                Type='SWITCH',
            },
            ClickBackToCamp={-- int (0)
                Type='SWITCH',
            },
            BeepOnNamed={-- int (0)
                Type='SWITCH',
            },
        },
    },
    GoM={
        Controls={
            On={
                Type='SWITCH',
            },
            COn=true,
        },
        Properties={
            GoM={
                Type='LIST',
                Max=5,
                Conditions=true,
            },
        },
    },
    AE={
        Controls={
            On={
                Type='SWITCH',
            },
        },
        Properties={
            AERadius={
                Type='NUMBER',
                Min=0,
            },
            AE={
                Type='LIST',
                Max=10,
                Conditions=false,
            },
        },
    },
    Aggro={
        Controls={
            On={
                Type='SWITCH',
            },
            COn=true,
        },
        Properties={
            Aggro={
                Type='LIST',
                Max=5,
                Conditions=true,
            },
        },
    },
    OhShit={
        Controls={
            On={
                Type='SWITCH',
            },
            COn=true,
        },
        Properties={
            OhShit={
                Type='LIST',
                Max=10,
                Conditions=true,
            },
        },
    },
    Bandolier={
        Controls={
            On={
                Type='SWITCH',
            },
            COn=true,
        },
        Properties={
            Bandolier={
                Type='LIST',
                Max=5,
                Conditions=true,
            },
            BandolierPull={
                Type='STRING',
            }
        },
    },
    Rogue={
        Classes={
            rog=1,
        },
        Properties={
            RogCorpseRetrieval={
                Type='SWITCH',
            },
            RogCorpseRadius={
                Type='NUMBER',
            },
        },
    },
    -- Gmail
      -- GmailOn, GMailSize, GMail
}

return schema
