local schema = {
    General={
        Properties={
            CampRadius={},
            CampRadiusExceed={},
            ReturnToCamp={
                Type='SWITCH'
            },
            ReturnToCampAccuracy={},
            ChaseAssist={},
            ChaseDistance={},
            MedOn={
                Type='SWITCH'
            },
            MedStart={},
            SitToMed={},
            LootOn={
                Type='SWITCH'
            },
            RezAcceptOn={},
            AcceptInvitesOn={
                Type='SWITCH'
            },
            GroupWatchOn={
                Type='SWITCH'
            },
            CastingInterruptOn={
                Type='SWITCH'
            },
            EQBCOn={
                Type='SWITCH'
            },
            DanNetOn={
                Type='SWITCH'
            },
            MiscGem={},
            MiscGemLW={},
            MiscGemRemem={},
            TwistOn={
                Type='SWITCH'
            },
            TwistMed={},
            TwistWhat={},
            GroupEscapeOn={
                Type='SWITCH'
            },
            CampfireOn={
                Type='SWITCH'
            },
            DPSMeter={
                Type='SWITCH'
            },
            CharInfo={},
            ScatterOn={
                Type='SWITCH'
            },
            DefaultUI={},
            CheerPeople={
                Type='SWITCH'
            },
            BeepOnNamed={
                Type='SWITCH'
            },
            BuffWhileChasing={
                Type='SWITCH'
            }
        }
    },
    SpellSet={
        Properties={
            LoadSpellSet={},
            SpellSetName={}
        }
    },
    Melee={
        Controls={
            On=true,
            COn=false
        },
        Properties={
            AssistAt={},
            FaceMobOn={
                Type='SWITCH'
            },
            MeleeDistance={},
            StickHow={},
            MeleeTwistOn={
                Type='SWITCH'
            },
            MeleeTwistWhat={},
            AutoFireOn={
                Type='SWITCH'
            },
            UseMQ2Melee={
                Type='SWITCH'
            },
            Autohide={
                Type='SWITCH'
            },
            BeforeCombat={}
        }
    },
    DPS={
        Controls={
            On=true,
            COn=true
        },
        Properties={
            DPS={
                Type='LIST',
                Max=40,
                Conditions=true
            },
            DPSSkip={},
            DPSInterval={},
            DebuffAllOn={
                Type='SWITCH'
            }
        }
    },
    Buffs={
        Controls={
            On=true,
            COn=true
        },
        Properties={
            Buffs={
                Type='LIST',
                Max=20,
                Conditions=true
            },
            RebuffOn={
                Type='SWITCH'
            },
            CheckBuffsTimer={},
            PowerSource={},
            BegOn={
                Type='SWITCH'
            },
            BegPermissions={},
            Beg={
                Type='LIST',
                Max=20,
                Conditions=false
            }
        }
    },
    Heals={
        Controls={
            On=true,
            COn=true
        },
        Properties={
            Heals={
                Type='LIST',
                Max=15,
                Conditions=true
            },
            XTarHeal={},
            AutoRezOn={
                Type='SWITCH'
            },
            AutoRezWith={},
            HealGroupPetsOn={
                Type='SWITCH'
            },
            InterruptHeals={
                Type='SWITCH'
            }
        }
    },
    Cures={
        Controls={
            On=true,
            COn=false
        },
        Properties={
            Cures={
                Type='LIST',
                Max=5,
                Conditions=false
            }
        }
    },
    Mez={
        Controls={
            On=true,
            COn=false
        },
        Classes={brd=1,enc=1},
        Properties={
            MezRadius={},
            MezMinLevel={},
            MezMaxLevel={},
            MezStopHPs={},
            MezSpell={
                Type='SPELL'
            },
            MezAESpell={
                Type='SPELL'
            }
        }
    },
    Pet={
        Controls={
            On=true,
            COn=false
        },
        Properties={
            PetSpell={
                Type='SPELL'
            },
            PetFocus={},
            PetShrinkOn={
                Type='SWITCH'
            },
            PetShrinkSpell={
                Type='SPELL'
            },
            PetHoldOn={
                Type='SWITCH'
            },
            PetBuffsOn={
                Type='SWITCH'
            },
            PetBuffs={
                Type='LIST',
                Max=8,
                Conditions=false
            },
            PetCombatOn={
                Type='SWITCH'
            },
            PetAssistAt={},
            PetBreakMezSpell={},
            PetRampPullWait={},
            PetSuspend={
                Type='SWITCH'
            },
            MoveWhenHit={
                Type='SWITCH'
            },
            PetForceHealOnMed={
                Type='SWITCH'
            }
        }
    },
    Pull={
        Properties={
            PullWith={},
            MaxRadius={},
            MaxZRange={},
            PullWait={},
            PullRoleToggle={},
            PullTwistOn={
                Type='SWITCH'
            },
            ChainPull={
                Type='SWITCH'
            },
            ChainPullHP={},
            PullPause={},
            PullLevel={},
            PullMeleeStick={
                Type='SWITCH'
            },
            UseWayPointZ={
                Type='SWITCH'
            },
            PullArcWidth={}
        }
    },
    Merc={
        Controls={
            On=true,
            COn=false
        },
        Properties={
            MercAssistAt={},
            AutoRevive={
                Type='SWITCH'
            }
        }
    },
    Burn={
        Properties={
            Burn={
                Type='LIST',
                Max=15,
                Conditions=false
            },
            BurnAllNamed={
                Type='SWITCH'
            }
        }
    },
    AFKTools={
        Controls={
            On=true,
            COn=false
        },
        Properties={
            AFKGMAction={},
            AFKPCRadius={},
            CampOnDeath={
                Type='SWITCH'
            },
            ClickBackToCamp={
                Type='SWITCH'
            },
            BeepOnNamed={
                Type='SWITCH'
            }
        }
    },
    GoM={
        Properties={
            GoM={
                Type='LIST',
                Max=5,
                Conditions=false
            }
        }
    },
    AE={
        Controls={
            On=true,
            COn=false
        },
        Properties={
            AERadius={},
            AE={
                Type='LIST',
                Max=10,
                Conditions=false
            }
        }
    },
    Aggro={
        Controls={
            On=true,
            COn=false
        },
        Properties={
            Aggro={
                Type='LIST',
                Max=5,
                Conditions=false
            }
        }
    },
    OhShit={
        Controls={
            On=true,
            COn=true
        },
        Properties={
            OhShit={
                Type='LIST',
                Max=10,
                Conditions=true
            }
        }
    }
}

return schema